import type { CultureRecord } from "./culture";

export type CuratedCultureRecord = Omit<CultureRecord, "id" | "createdAt" | "updatedAt">;

const yearRound = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
const nationalLocation = {
  state: "India",
  region: "National",
  coordinates: [78.9629, 20.5937] as [number, number],
};

const unesco = (title: string, url: string) => ({
  title,
  publisher: "UNESCO Intangible Cultural Heritage",
  url,
  confidence: "official" as const,
});

const ministryOfTourism = (title: string, url: string) => ({
  title,
  publisher: "Ministry of Tourism, Government of India",
  url,
  confidence: "official" as const,
});

export const curatedCulturePilot: CuratedCultureRecord[] = [
  {
    slug: "deepavali",
    title: "Deepavali",
    category: "festival",
    summary: "A widely observed Indian festival of lights, recognized on UNESCO's Representative List in 2025.",
    history: "UNESCO's India register records Deepavali as an inscribed element on the Representative List of the Intangible Cultural Heritage of Humanity.",
    culturalImportance: "The festival brings households and communities together through light, ritual, visiting, and shared observance.",
    impact: "Its annual return connects a living religious and social practice across many regions and diasporic communities.",
    location: nationalLocation,
    seasonMonths: [10, 11],
    bestVisitingTime: "October–November; dates vary with the lunisolar calendar.",
    source: unesco("Deepavali", "https://ich.unesco.org/en/RL/deepavali-02312"),
    status: "approved",
  },
  {
    slug: "nawrouz-in-india",
    title: "Nawrouz in India",
    category: "festival",
    summary: "The spring new-year observance is represented in UNESCO's 2024 multinational Nawrouz inscription.",
    history: "UNESCO's India register includes India in the multi-country Nawrouz element inscribed in 2024.",
    culturalImportance: "The observance marks renewal and sustains cultural links among communities that celebrate the new year in spring.",
    impact: "It provides a cross-cultural lens on shared seasonal traditions that extend beyond one locality.",
    location: nationalLocation,
    seasonMonths: [3],
    bestVisitingTime: "March; confirm local community dates before travel.",
    source: unesco("Nawrouz", "https://ich.unesco.org/en/RL/nawrouz-novruz-nowrouz-nowrouz-nawrouz-nauryz-nooruz-nowruz-navruz-nevruz-nowruz-navruz-02097"),
    status: "approved",
  },
  {
    slug: "garba-of-gujarat",
    title: "Garba of Gujarat",
    category: "festival",
    summary: "A Gujarati dance tradition associated with the Navratri season and inscribed on UNESCO's Representative List.",
    history: "UNESCO's India register identifies Garba as an element of Gujarat on the Representative List.",
    culturalImportance: "Circular dance, music, and collective participation make Garba a visible expression of seasonal community celebration.",
    impact: "The practice sustains intergenerational performance knowledge and public cultural participation.",
    location: { state: "Gujarat", region: "West India", coordinates: [72.5714, 23.0225] },
    seasonMonths: [9, 10],
    bestVisitingTime: "September–October during Navratri; dates vary annually.",
    source: unesco("Garba of Gujarat", "https://ich.unesco.org/en/RL/garba-of-gujarat-01962"),
    status: "approved",
  },
  {
    slug: "durga-puja-in-kolkata",
    title: "Durga Puja in Kolkata",
    category: "festival",
    summary: "A ten-day autumn festival in Kolkata combining worship, clay-image making, drumming, art, and public installations.",
    history: "UNESCO describes the festival as an annual September or October observance, inscribed in 2021.",
    culturalImportance: "It brings artisans, designers, worshippers, and visitors into a shared urban cultural season.",
    impact: "The festival supports collaborative creative practice alongside longstanding ritual observance.",
    location: { state: "West Bengal", region: "East India", coordinates: [88.3639, 22.5726] },
    seasonMonths: [9, 10],
    bestVisitingTime: "September–October; dates vary with the festival calendar.",
    source: unesco("Durga Puja in Kolkata", "https://ich.unesco.org/en/RL/durga-puja-in-kolkata-00703"),
    status: "approved",
  },
  {
    slug: "kumbh-mela",
    title: "Kumbh Mela",
    category: "festival",
    summary: "A rotating sacred-river pilgrimage held at Prayagraj, Haridwar, Ujjain, and Nashik.",
    history: "UNESCO inscribed Kumbh Mela in 2017 and describes the event's combination of astronomy, ritual, social practice, and knowledge transmission.",
    culturalImportance: "The gathering connects ascetics, religious organizations, pilgrims, and visitors through shared river-bathing and observance.",
    impact: "Its rotating host cities demonstrate how one tradition takes different local forms across India.",
    location: { state: "Uttar Pradesh", region: "North India", coordinates: [81.8463, 25.4358] },
    seasonMonths: [1, 2, 3, 4],
    bestVisitingTime: "Dates and host city rotate; consult the current official Kumbh schedule.",
    source: unesco("Kumbh Mela", "https://ich.unesco.org/en/RL/kumbh-mela-01258"),
    status: "approved",
  },
  {
    slug: "hornbill-festival",
    title: "Hornbill Festival",
    category: "festival",
    summary: "A ten-day Nagaland cultural showcase bringing together performances, crafts, indigenous games, and cuisine.",
    history: "The Ministry of Tourism records the event as a State Government initiative conceptualized in 2000.",
    culturalImportance: "It creates a shared setting for Naga communities to present cultural diversity, craftsmanship, and performance.",
    impact: "The festival supports cultural visibility and creates a public platform for heritage-based tourism.",
    location: { state: "Nagaland", region: "Northeast India", coordinates: [94.1406, 25.6408] },
    seasonMonths: [12],
    bestVisitingTime: "Early December; confirm current annual dates with Nagaland Tourism.",
    source: ministryOfTourism("Hornbill Festival", "https://utsav.gov.in/public/view-event/hornbill-festival"),
    status: "approved",
  },
  {
    slug: "pongal-festival",
    title: "Pongal",
    category: "festival",
    summary: "A four-day Tamil harvest observance that honours nature, rain, the Sun, cattle, and communal food.",
    history: "The Ministry of Tourism's Utsav record describes the festival's four successive days of observance in January.",
    culturalImportance: "The celebration foregrounds gratitude for agriculture, animals, and seasonal abundance.",
    impact: "Ritual, food, and family gatherings keep a regional harvest tradition visible in public life.",
    location: { state: "Tamil Nadu", region: "South India", coordinates: [80.2707, 13.0827] },
    seasonMonths: [1],
    bestVisitingTime: "Mid-January; confirm the annual Tamil calendar dates.",
    source: ministryOfTourism("Harvest Festival", "https://utsav.gov.in/public/event-category/harvest-festival"),
    status: "approved",
  },
  {
    slug: "makar-sankranti",
    title: "Makar Sankranti",
    category: "festival",
    summary: "A mid-January solar festival marking the Sun's movement into Capricorn and the Uttarayan period.",
    history: "The Ministry of Tourism's harvest-festival page identifies Makar Sankranti with the transition out of shorter winter days.",
    culturalImportance: "The festival expresses seasonal change through kites, food, prayer, and regional celebrations.",
    impact: "Its varied regional forms show how a shared astronomical marker is interpreted across India.",
    location: nationalLocation,
    seasonMonths: [1],
    bestVisitingTime: "Mid-January.",
    source: ministryOfTourism("Harvest Festival", "https://utsav.gov.in/public/event-category/harvest-festival"),
    status: "approved",
  },
  {
    slug: "lohri",
    title: "Lohri",
    category: "festival",
    summary: "A North Indian winter festival associated with bonfires, seasonal foods, and community gathering.",
    history: "The Ministry of Tourism's harvest-festival page records its observance on 13 January and notes its roots in Punjab.",
    culturalImportance: "Bonfire rituals and shared foods create a communal marker of the winter season.",
    impact: "The festival continues to connect seasonal customs, family life, and local identity.",
    location: { state: "Punjab", region: "North India", coordinates: [75.8573, 30.9009] },
    seasonMonths: [1],
    bestVisitingTime: "13 January.",
    source: ministryOfTourism("Harvest Festival", "https://utsav.gov.in/public/event-category/harvest-festival"),
    status: "approved",
  },
  {
    slug: "yoga",
    title: "Yoga",
    category: "tradition",
    summary: "An Indian practice integrating poses, meditation, controlled breathing, chanting, and related techniques.",
    history: "UNESCO inscribed Yoga in 2016 and describes its traditional Guru-Shishya transmission alongside contemporary learning settings.",
    culturalImportance: "Yoga connects physical practice with philosophical, spiritual, educational, and community traditions.",
    impact: "Its practice and teaching remain part of cultural life in India while reaching learners internationally.",
    location: nationalLocation,
    seasonMonths: yearRound,
    bestVisitingTime: "Year-round; programmes vary by location.",
    source: unesco("Yoga", "https://ich.unesco.org/en/RL/yoga-01163"),
    status: "approved",
  },
  {
    slug: "thatheras-utensil-craft",
    title: "Thatheras’ Brass and Copper Utensil Craft",
    category: "tradition",
    summary: "A traditional metal-utensil making practice associated with Jandiala Guru in Punjab.",
    history: "UNESCO's India register identifies the craft among the Thatheras of Jandiala Guru, Punjab.",
    culturalImportance: "The practice preserves specialized knowledge of shaping and finishing metal household vessels.",
    impact: "Recognizing the craft supports attention to artisanal transmission and living material culture.",
    location: { state: "Punjab", region: "North India", coordinates: [74.7518, 31.5628] },
    seasonMonths: yearRound,
    bestVisitingTime: "Year-round; arrange artisan visits respectfully in advance.",
    source: unesco("Traditional brass and copper craft of utensil making among the Thatheras of Jandiala Guru, Punjab, India", "https://ich.unesco.org/en/RL/traditional-brass-and-copper-craft-of-utensil-making-among-the-thatheras-of-jandiala-guru-punjab-india-00845"),
    status: "approved",
  },
  {
    slug: "sankirtana-manipur",
    title: "Sankirtana of Manipur",
    category: "tradition",
    summary: "A Manipur practice of ritual singing, drumming, and dancing.",
    history: "UNESCO's India register identifies Sankirtana as an inscribed ritual performance tradition of Manipur.",
    culturalImportance: "Music, movement, and ritual combine in a practice passed through performance and community participation.",
    impact: "Its safeguarding keeps an integrated musical and ceremonial tradition active in Manipur.",
    location: { state: "Manipur", region: "Northeast India", coordinates: [93.9368, 24.817] },
    seasonMonths: yearRound,
    bestVisitingTime: "Year-round; performance calendars are locally determined.",
    source: unesco("Sankirtana, ritual singing, drumming and dancing of Manipur", "https://ich.unesco.org/en/RL/sankirtana-ritual-singing-drumming-and-dancing-of-manipur-00843"),
    status: "approved",
  },
  {
    slug: "chhau-dance",
    title: "Chhau Dance",
    category: "tradition",
    summary: "An eastern Indian dance tradition recognized by UNESCO.",
    history: "UNESCO's India register lists Chhau dance among India's Representative List elements.",
    culturalImportance: "The tradition brings stylized movement, music, and local performance lineages into public cultural life.",
    impact: "It provides a shared heritage lens across eastern Indian communities associated with Chhau practice.",
    location: { state: "West Bengal", region: "East India", coordinates: [86.3652, 23.3321] },
    seasonMonths: yearRound,
    bestVisitingTime: "Year-round; local performance schedules vary.",
    source: unesco("Chhau dance", "https://ich.unesco.org/en/RL/chhau-dance-00337"),
    status: "approved",
  },
  {
    slug: "kalbelia-folk-songs-and-dances",
    title: "Kalbelia Folk Songs and Dances",
    category: "tradition",
    summary: "A Rajasthan performance tradition of folk song and dance recognized on UNESCO's Representative List.",
    history: "UNESCO's India register lists Kalbelia folk songs and dances of Rajasthan as an inscribed element.",
    culturalImportance: "The tradition makes music, movement, costume, and community memory visible through performance.",
    impact: "It supports recognition of a living Rajasthan performance heritage.",
    location: { state: "Rajasthan", region: "West India", coordinates: [75.7873, 26.9124] },
    seasonMonths: yearRound,
    bestVisitingTime: "Year-round; consult local cultural calendars.",
    source: unesco("Kalbelia folk songs and dances of Rajasthan", "https://ich.unesco.org/en/RL/kalbelia-folk-songs-and-dances-of-rajasthan-00340"),
    status: "approved",
  },
  {
    slug: "mudiyettu",
    title: "Mudiyettu",
    category: "tradition",
    summary: "A Kerala ritual theatre and dance-drama tradition recognized by UNESCO.",
    history: "UNESCO's India register identifies Mudiyettu as a ritual theatre and dance drama of Kerala.",
    culturalImportance: "It holds ritual, narrative, music, and embodied performance together in a community practice.",
    impact: "Its listing draws attention to local artistic transmission and ceremonial performance.",
    location: { state: "Kerala", region: "South India", coordinates: [76.2673, 9.9312] },
    seasonMonths: yearRound,
    bestVisitingTime: "Year-round; temple and community schedules vary.",
    source: unesco("Mudiyettu, ritual theatre and dance drama of Kerala", "https://ich.unesco.org/en/RL/mudiyettu-ritual-theatre-and-dance-drama-of-kerala-00345"),
    status: "approved",
  },
  {
    slug: "kutiyattam",
    title: "Kutiyattam, Sanskrit Theatre",
    category: "tradition",
    summary: "A Kerala Sanskrit theatre tradition recognized on UNESCO's Representative List.",
    history: "UNESCO's India register lists Kutiyattam as an inscribed Sanskrit theatre element.",
    culturalImportance: "The form preserves a long-form theatrical practice rooted in language, gesture, music, and performance training.",
    impact: "It sustains a distinct theatre lineage and makes its specialized artistic vocabulary visible to new audiences.",
    location: { state: "Kerala", region: "South India", coordinates: [76.2673, 9.9312] },
    seasonMonths: yearRound,
    bestVisitingTime: "Year-round; check venue-specific programmes.",
    source: unesco("Kutiyattam, Sanskrit theatre", "https://ich.unesco.org/en/RL/kutiyattam-sanskrit-theatre-00010"),
    status: "approved",
  },
  {
    slug: "appam",
    title: "Appam",
    category: "food",
    summary: "A fermented rice-batter and coconut-milk preparation commonly served for breakfast or dinner in Kerala.",
    history: "Incredible India's Kochi food guide documents appam as a regional preparation made from fermented rice batter and coconut milk.",
    culturalImportance: "The dish reflects a widely recognized Kerala food practice centered on everyday ingredients and meal sharing.",
    impact: "Documenting the dish alongside festivals and arts broadens cultural discovery to everyday culinary knowledge.",
    location: { state: "Kerala", region: "South India", coordinates: [76.2673, 9.9312] },
    seasonMonths: yearRound,
    bestVisitingTime: "Year-round.",
    source: ministryOfTourism("Food and Cuisine | Incredible India", "https://prod.incredibleindia.gov.in/content/incredible-india-v2/en/destinations/kochi/food-and-cuisine.html"),
    status: "approved",
  },
  {
    slug: "thalassery-biriyani",
    title: "Thalassery Biriyani",
    category: "food",
    summary: "A Malabar-coast biriyani associated with fragrant basmati rice, meat, spices, fried onions, cashews, and raisins.",
    history: "Incredible India's Kerala food guide identifies Thalassery Biriyani as a distinctive Malabar-coast dish.",
    culturalImportance: "It represents a regional culinary expression within the many biriyani traditions enjoyed across India.",
    impact: "Including a place-linked food record helps visitors connect cuisine with regional cultural geography.",
    location: { state: "Kerala", region: "South India", coordinates: [75.4836, 11.748] },
    seasonMonths: yearRound,
    bestVisitingTime: "Year-round.",
    source: ministryOfTourism("What to Eat and Where to Eat in Thiruvananthapuram", "https://www.incredibleindia.gov.in/en/kerala/thiruvananthapuram/what-to-eat-and-where-to-eat-in-thiruvananthapuram"),
    status: "approved",
  },
  {
    slug: "pongal-sweet",
    title: "Pongal Sweet",
    category: "food",
    summary: "A sweet offering prepared during the Pongal harvest observance and offered to the Sun on its auspicious second day.",
    history: "The Ministry of Tourism's harvest-festival record describes the making of Pongal sweet during the four-day January observance.",
    culturalImportance: "The preparation ties seasonal food to ritual gratitude and the agricultural cycle.",
    impact: "Its inclusion highlights how food can be both an everyday practice and a ceremonial cultural expression.",
    location: { state: "Tamil Nadu", region: "South India", coordinates: [80.2707, 13.0827] },
    seasonMonths: [1],
    bestVisitingTime: "Mid-January during Pongal.",
    source: ministryOfTourism("Harvest Festival", "https://utsav.gov.in/public/event-category/harvest-festival"),
    status: "approved",
  },
  {
    slug: "ramlila",
    title: "Ramlila",
    category: "story",
    summary: "A traditional performance of the Ramayana recognized on UNESCO's Representative List.",
    history: "UNESCO's India register lists Ramlila as an inscribed traditional performance of the Ramayana.",
    culturalImportance: "The performance transmits a major narrative tradition through community staging, dialogue, music, and ritual context.",
    impact: "Its continuing practice keeps oral, theatrical, and narrative heritage accessible in public settings.",
    location: nationalLocation,
    seasonMonths: [9, 10],
    bestVisitingTime: "September–October; dates and local performance cycles vary.",
    source: unesco("Ramlila, the traditional performance of the Ramayana", "https://ich.unesco.org/en/RL/ramlila-the-traditional-performance-of-the-ramayana-00110"),
    status: "approved",
  },
  {
    slug: "vedic-chanting",
    title: "Tradition of Vedic Chanting",
    category: "story",
    summary: "An oral tradition recognized by UNESCO's Representative List.",
    history: "UNESCO's India register lists the Tradition of Vedic chanting as an inscribed element.",
    culturalImportance: "The practice preserves oral transmission through sound, recitation, and teacher-student learning.",
    impact: "It draws attention to the cultural importance of oral knowledge systems and careful transmission.",
    location: nationalLocation,
    seasonMonths: yearRound,
    bestVisitingTime: "Year-round; access depends on local institutions and observances.",
    source: unesco("Tradition of Vedic chanting", "https://ich.unesco.org/en/RL/tradition-of-vedic-chanting-00062"),
    status: "approved",
  },
  {
    slug: "buddhist-chanting-ladakh",
    title: "Buddhist Chanting of Ladakh",
    category: "story",
    summary: "The recitation of sacred Buddhist texts in Ladakh's trans-Himalayan region.",
    history: "UNESCO's India register lists Buddhist chanting of Ladakh as an inscribed element focused on recitation of sacred texts.",
    culturalImportance: "The practice carries religious philosophy and teaching through living oral performance.",
    impact: "It recognizes the role of monastic and community transmission in preserving a regional oral tradition.",
    location: { state: "Ladakh", region: "North India", coordinates: [77.577, 34.1526] },
    seasonMonths: yearRound,
    bestVisitingTime: "Year-round; access and local observance vary by monastery and season.",
    source: unesco("Buddhist chanting of Ladakh", "https://ich.unesco.org/en/RL/buddhist-chanting-of-ladakh-recitation-of-sacred-buddhist-texts-in-the-trans-himalayan-ladakh-region-jammu-and-kashmir-india-00839"),
    status: "approved",
  },
];
